# Image used as the build agent by Jenkins

FROM python:3.9.16-slim

# install base requirements
RUN apt-get update && apt-get install -y \
    make

# install robot framework
RUN pip install --no-cache-dir robotframework
